import "./style.css";
import { Container, Row, Col } from "react-bootstrap";

const TAndC = () => {
  return (
    <>
      <main className="terms">
        <Container>
          <Row>
            <Col lg={12}>
              <h1 className="text-center">Terms of Service</h1>
              <br />
              <br />

              <h2>Terms Of Sale</h2>

              <p>
                PLEASE READ THESE TERMS OF SALE CAREFULLY BEFORE ORDERING
                PRODUCTS ONLINE FROM THE DRAKE RELATED PLATFORM. PLEASE, NOTE
                THAT THESE TERMS OF SALE INCLUDE THE ADDITIONAL TERMS
                INCORPORATED HEREIN BY REFERENCE. PURCHASES MADE IN AUSTRALIA,
                CANADA, EGYPT, INDIA, INDONESIA, ISRAEL, MALAYSIA, MEXICO,
                MOROCCO, NEW ZEALAND, PHILIPPINES, PUERTO RICO, RUSSIA, SAUDI
                ARABIA, SINGAPORE, SOUTH AFRICA, TAIWAN, THAILAND, UNITED ARAB
                EMIRATES, AND VIETNAM ARE GOVERNED BY DIFFERENT TERMS.
              </p>

              <p>
                IF YOU ARE LOCATED IN ANY OF THE COUNTRIES IDENTIFIED BELOW,
                ADDITIONAL COUNTRY-SPECIFIC TERMS MAY APPLY TO YOU AND ARE
                VIEWABLE AT THE END OF THESE TERMS OF SALE OR BY CLICKING ON THE
                COUNTRY REFERENCE LINK. THESE ADDITIONAL TERMS OVERRIDE THE
                TERMS BELOW TO THE EXTENT OF ANY INCONSISTENCY. <br />
                CHINA, COSTA RICA, DOMINICAN REPUBLIC, KOREA.
              </p>

              <h2>APPLICABILITY</h2>
              <p>
                YOU ARE READING THESE TERMS OF SALE (“TERMS OF SALE”) BECAUSE
                YOU ARE USING A DRAKE REALTED WEBSITE, DIGITAL EXPERIENCE,
                SOCIAL MEDIA PLATFORM, MOBILE APP, WEARABLE TECHNOLOGY, OR ONE
                OF OUR OTHER PRODUCTS OR SERVICES, ALL OF WHICH ARE PART OF
                DRAKE REALTED’S PLATFORM (“PLATFORM”). THESE TERMS OF SALE
                CREATE A LEGALLY BINDING AGREEMENT BETWEEN YOU AND DRAKE REALTED
                AND ITS AFFILIATES (WHICH WE MAY REFER TO AS “DRAKE REALTED ,”
                “WE,” “US,” OR “OUR”) REGARDING ORDERS PLACED FOR PRODUCTS
                AVAILABLE ON THE PLATFORM. DRAKE REALTED MAY REVISE THESE TERMS
                OF SALE WITHOUT NOTICE BY POSTING REVISED TERMS OF SALE ON ITS
                PLATFORM. THE TERMS OF SALE POSTED ON THE PLATFORM AT THE TIME
                YOU PLACE YOUR ORDER ON THE PLATFORM WILL GOVERN THAT PURCHASE.
                PLEASE READ THESE TERMS CAREFULLY AND CHECK THAT THE DETAILS OF
                YOUR ORDER ARE COMPLETE AND ACCURATE BEFORE SUBMITTING YOUR
                ORDER. IF YOU THINK THAT THERE IS A MISTAKE, PLEASE CONTACT US:
                <a href="mailto:cs@tertiusahmanuph.co">CS@tertiusahmanuph.co</a>
                . DRAKE REALTED TERMS OF USE AND PRIVACY POLICY ARE INCORPORATED
                HEREIN BY THIS REFERENCE.
              </p>

              <h2>PLACING ORDERS ON THE PLATFORM</h2>
              <h3>ELIGIBILITY TO ORDER</h3>

              <p>
                TO PLACE AN ORDER ON THE PLATFORM, YOU MUST BE OF LEGAL AGE IN
                YOUR COUNTRY AND A CONSUMER. “PRODUCT(S)” SHALL MEAN ANY GOODS
                PURCHASED THROUGH THIS SITE, AND ANY SUBDOMAINS. DRAKE REALTED
                MAY CHANGE THE PRODUCT (I) TO REFLECT ANY CHANGES IN RELEVANT
                LAWS AND REGULATORY REQUIREMENTS AND (II) TO IMPLEMENT MINOR
                TECHNICAL ADJUSTMENTS AND IMPROVEMENTS. THESE CHANGES WILL NOT
                AFFECT THE CLIENT'S USE OF THE PRODUCT.
              </p>

              <h2>ORDER PROCESS, PAYMENT, AND ELECTRONIC COMMUNICATIONS.</h2>

              <p>IF YOU PLACE ANY ORDERS FOR PRODUCTS ON THE SITE, YOU ARE EXPRESSLY AGREEING THAT DRAKE REALTED IS PERMITTED TO BILL YOU THE APPLICABLE FEES, ANY APPLICABLE TAX AND ANY OTHER CHARGES YOU MAY INCUR WITH DRAKE REALTED YOU AGREE THAT THE FEES WILL BE BILLED TO YOUR PAYMENT CARD YOU PROVIDE IN ACCORDANCE WITH THE BILLING TERMS IN EFFECT AT THE TIME A FEE OR CHARGE IS DUE AND PAYABLE, AS APPLICABLE. ALL BILLING INFORMATION MUST MATCH THE SHIPPING ADDRESS, NO EXCEPTIONS. NO ORDERS, BILLING INFORMATION, OR PURCHASES MADE BY A CUSTOMER OUTSIDE THE UNITED STATES (AND IN THOSE INSTANCES IDENTIFIED IN THE PRODUCTS LISTING, THOSE EXCLUDED STATES WITHIN THE UNITED STATES) WILL BE ACCEPTED, OR PROCESSED. IF PAYMENT IS NOT RECEIVED OR CANNOT BE CHARGED TO YOUR PAYMENT CARD FOR ANY REASON IN ADVANCE OF SHIPPING YOUR ORDER, DRAKE REALTED RESERVES THE RIGHT TO EITHER SUSPEND OR TERMINATE YOUR ORDER.</p>
            </Col>
          </Row>
        </Container>
      </main>
    </>
  );
};

export default TAndC;
